version: "{build}"

skip_tags: true

environment:
  libintl: "https://github.com/maxwell-k/libintl-appveyor/releases/\
    download/0.19.5.1.97/"
  mirrors: pacman-mirrors-20150722-1-any.pkg.tar.xz

cache:
  - '%mirrors%'
  - C:\msys64\var\cache\pacman\pkg\zip-3.0-1-x86_64.pkg.tar.xz

init: # Simplify the PATH variable
  - "set PATH=%SystemRoot%\\system32;%SystemRoot%;\
    %SystemRoot%\\System32\\Wbem;\
    C:\\Program Files\\7-Zip;\
    C:\\Program Files (x86)\\Git\\cmd;\
    C:\\Program Files\\AppVeyor\\BuildAgent"

install: # Install prerequisites
  - .\msys2.bat
  - "C:\\msys64\\usr\\bin\\sh --login -c \"
      pacman -S --needed --noconfirm zip
    \" > nul 2> nul"

before_build: # Download content
  - appveyor DownloadFile %libintl%/libintl-8.dll
  - appveyor DownloadFile %libintl%/release.sha256
  - "C:\\msys64\\usr\\bin\\sh --login -c \"
      sha256sum -c release.sha256
    \""
  - git submodule update --init

build_script: # Compile with Visual Studio
  - 'cd "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\"'
  - .\SetEnv.cmd /x64 /release > nul
  - cd %APPVEYOR_BUILD_FOLDER%\vim\src
  - >
      nmake -f Make_mvc.mak CPU=AMD64 GUI=yes IME=yes MBYTE=yes ICONV=yes
      DEBUG=no PYTHON_VER=27 DYNAMIC_PYTHON=yes PYTHON=C:\Python27-x64
      PYTHON3_VER=34 DYNAMIC_PYTHON3=yes PYTHON3=C:\Python34-x64
      > nul 2> nul
  - cd %APPVEYOR_BUILD_FOLDER%\vim\src\po
  - nmake -f Make_mvc.mak GETTEXT_PATH=C:\msys64\usr\bin\ all > nul 2> nul

after_build: # Package with MSYS2
  - set MSYSTEM=MINGW64
  - "C:\\msys64\\usr\\bin\\sh --login -c \"
      cd vim &&
      cp
        src/gvim.exe
        src/vimrun.exe
        src/GvimExt/gvimext.dll
        src/gvim.pdb
        . &&
      cp src/xxd/xxd.exe xxdw32.exe &&
      cp src/install.exe installw32.exe &&
      cp src/uninstal.exe uninstalw32.exe &&
      make VIM=./gvim.exe dosbin_gvim
    \" > nul 2> nul"
  - "C:\\msys64\\usr\\bin\\sh --login -c \"
      cd vim &&
      touch src/auto/config.mk &&
      rm src/po/Makefile &&
      cp ../libintl-8.dll libintl.dll &&
      make VIM=./gvim.exe dosrt
    \" > nul 2> nul"
  - "C:\\msys64\\usr\\bin\\sh --login -c \"
      cp vim/dist/gvim74.zip . &&
      cp vim/dist/vim74rt.zip . &&
      sha256sum gvim74.zip > gvim74.zip.sha256 &&
      sha256sum vim74rt.zip > vim74rt.zip.sha256
    \""

before_test:
  - cd %APPVEYOR_BUILD_FOLDER%\vim
  - .\gvim -u NONE -c "redir @a | version | 0put a | wq!" version.txt
  - type version.txt && del version.txt

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\vim\src\testdir
  # needs unix tools like diff; use MSYS2 versions
  - set PATH=C:\msys64\usr\bin;%PATH%
  - nmake -f Make_dos.mak VIMPROG=..\..\gvim > nul

on_failure:
  - ps: "$blockRdp = $true; iex ((new-object net.webclient).DownloadString((\
      'https://raw.githubusercontent.com/appveyor/ci/master/scripts/\
      enable-rdp.ps1')))"

artifacts:
  - path: gvim74.zip
  - path: gvim74.zip.sha256
  - path: vim74rt.zip
  - path: vim74rt.zip.sha256

before_deploy: # Find the vim version for the release label
  - cd %APPVEYOR_BUILD_FOLDER%\vim
  - git rev-parse HEAD | git name-rev --stdin --name-only --tags > ../tag
  - cd .. && set /P github_release= < tag && del /Q tag
  - echo Built release %github_release%.%APPVEYOR_BUILD_NUMBER%

deploy:
  release: $(github_release).$(APPVEYOR_BUILD_NUMBER)
  description: "[AppVeyor build](https://ci.appveyor.com/project/\
    $(APPVEYOR_REPO_NAME)/build/$(APPVEYOR_BUILD_VERSION))"
  provider: GitHub
  draft: true
  on: { appveyor_repo_tag: false }
  auth_token:
    secure: qty+OleXdcHipnzD0RGUfPbTpe5Q9WtPvIknOFhkaIzQ28ccEsMU1mKSKQ2lnLUn
